// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2024 Josh Poimboeuf <jpoimboe@kernel.org>
 */

#define _GNU_SOURCE
#include <string.h>
#include <libgen.h>
#include <stdio.h>
#include <objtool/objtool.h>
#include <objtool/warn.h>
#include <objtool/arch.h>
#include <objtool/klp.h>
#include <linux/livepatch_ext.h>
#include <linux/stringify.h>
#include <linux/string.h>
#include <linux/jhash.h>

#define ALIGN_DOWN(x, align_to) ((x) & ~((align_to)-1))
#define sizeof_field(TYPE, MEMBER) sizeof((((TYPE *)0)->MEMBER))

struct elfs {
	struct elf *orig, *patched, *out;
};

struct export {
	struct hlist_node hash;
	char *mod, *sym;
};

static DEFINE_HASHTABLE(exports, 15);

static inline u32 str_hash(const char *str)
{
	return jhash(str, strlen(str), 0);
}

static void read_exports(void)
{
	const char *symvers = "Module.symvers";
	char line[1024];
	FILE *file;

	file = fopen(symvers, "r");
	ERROR_ON(!file, "can't open '%s', \"objtool diff\" should be run from the kernel tree", symvers);

	while (fgets(line, 1024, file)) {
		char *sym, *mod, *exp;
		struct export *export;

		sym = strchr(line, '\t');
		ERROR_ON(!sym, "malformed Module.symvers");

		*sym++ = '\0';

		mod = strchr(sym, '\t');
		ERROR_ON(!mod, "malformed Module.symvers");

		*mod++ = '\0';

		exp = strchr(mod, '\t');
		ERROR_ON(!exp, "malformed Module.symvers");

		*exp++ = '\0';

		ERROR_ON(*sym == '\0' || *mod == '\0', "malformed Module.symvers");

		export = calloc(1, sizeof(*export));
		ERROR_ON(!export, "calloc");

		export->mod = strdup(mod);
		export->sym = strdup(sym);
		hash_add(exports, &export->hash, str_hash(sym));
	}
}

static int read_sym_checksums(struct elf *elf)
{
	struct section *sec;

	sec = find_section_by_name(elf, SYM_CHECKSUM_SEC);
	if (!sec)
		return 0;

	if (!sec->rsec)
		ERROR("missing reloc section for " SYM_CHECKSUM_SEC);

	if (sec_size(sec) % sizeof(struct sym_checksum))
		ERROR("struct sym_checksum size mismatch");

	for (int i = 0; i < sec_size(sec) / sizeof(struct sym_checksum); i++) {
		struct sym_checksum *sym_checksum;
		struct reloc *reloc;
		struct symbol *sym;

		sym_checksum = (struct sym_checksum *)sec->data->d_buf + i;

		reloc = find_reloc_by_dest(elf, sec, i * sizeof(*sym_checksum));
		if (!reloc)
			ERROR("can't find reloc for sym_checksum[%d]", i);

		sym = reloc->sym;

		if (is_section_symbol(sym))
			ERROR("not sure how to handle section %s", sym->name);

		if (is_function_symbol(sym))
			sym->checksum = sym_checksum->checksum;
	}

	return 0;
}
static struct symbol *first_file_symbol(struct elf *elf)
{
	struct symbol *sym;

	for_each_sym(elf, sym)
		if (is_file_symbol(sym))
			return sym;

	return NULL;
}

static struct symbol *next_file_symbol(struct elf *elf, struct symbol *sym)
{
	for_each_sym_continue(elf, sym)
		if (is_file_symbol(sym))
			return sym;

	return NULL;
}

/*
 * Certain static local variables should never be correlated.  They will be
 * used in place rather than referencing the originals.
 */
static bool is_uncorrelated_static_local(struct symbol *sym)
{
	static const char * const vars[] = {
		"__key.",
		"__warned.",
		"__already_done.",
		"__func__.",
		"_rs.",
		"CSWTCH.",
	};

	if (!is_object_symbol(sym) || !is_local_symbol(sym))
		return false;

	if (!strcmp(sym->sec->name, ".data.once"))
		return true;

	for (int i = 0; i < ARRAY_SIZE(vars); i++) {
		if (strstarts(sym->name, vars[i]))
			return true;
	}

	return false;
}

static bool is_special_section(struct section *sec)
{
	static const char * const specials[] = {
		".altinstructions",
		".smp_locks",
		"__bug_table",
		"__ex_table",
		"__jump_table",
		"__mcount_loc",
		/*
		 * .static_call_sites is generated by "objtool --static-call"
		 * which will run again later at livepatch module link time.
		 * So one might be forgiven for thinking it doesn't need to be
		 * extracted here.
		 *
		 * However, when run on modules, objtool blocks access to
		 * unexported static call keys.
		 *
		 * So extract it here to inherit the non-module preferential
		 * treatment.  The later static call processing will be skipped
		 * when it sees this section already exists.
		 */
		".static_call_sites",
	};

	static const char * const non_special_discards[] = {
		".discard.addressable",
		SYM_CHECKSUM_SEC,
	};

	for (int i = 0; i < ARRAY_SIZE(specials); i++)
		if (!strcmp(sec->name, specials[i]))
			return true;

	/* Most .discard sections are special */
	for (int i = 0; i < ARRAY_SIZE(non_special_discards); i++)
		if (!strcmp(sec->name, non_special_discards[i]))
			return false;
	return strstarts(sec->name, ".discard.");
}

/*
 * These sections are referenced by special sections but aren't considered
 * special sections themselves.
 */
static bool is_special_section_aux(struct section *sec)
{
	static const char * const specials_aux[] = {
		".altinstr_replacement",
		".altinstr_aux",
	};

	for (int i = 0; i < ARRAY_SIZE(specials_aux); i++)
		if (!strcmp(sec->name, specials_aux[i]))
			return true;

	return false;
}

/*
 * These symbols should never be correlated, so their local patched versions
 * are used instead of linking to the originals.
 */
static bool dont_correlate(struct symbol *sym)
{
	return is_file_symbol(sym) ||
	       is_null_symbol(sym) ||
	       is_section_symbol(sym) ||
	       is_prefix_symbol(sym) ||
	       is_uncorrelated_static_local(sym) ||
	       is_string_section(sym->sec) ||
	       is_special_section(sym->sec) ||
	       is_special_section_aux(sym->sec) ||
	       strstarts(sym->name, "__initcall__");
}

/*
 * For each symbol in the original kernel, find its corresponding "twin" in the
 * patched kernel.
 */
static void correlate_symbols(struct elfs *e)
{
	struct symbol *file1_sym, *file2_sym;
	struct symbol *sym1, *sym2;

	/* Correlate locals */
	for (file1_sym = first_file_symbol(e->orig),
	     file2_sym = first_file_symbol(e->patched); ;
	     file1_sym = next_file_symbol(e->orig, file1_sym),
	     file2_sym = next_file_symbol(e->patched, file2_sym)) {

		if (!file1_sym && file2_sym)
			ERROR("FILE symbol mismatch: NULL != %s", file2_sym->name);

		if (file1_sym && !file2_sym)
			ERROR("FILE symbol mismatch: %s != NULL", file1_sym->name);

		if (!file1_sym)
			break;

		if (strcmp(file1_sym->name, file2_sym->name))
			ERROR("FILE symbol mismatch: %s != %s",file1_sym->name, file2_sym->name);

		file1_sym->twin = file2_sym;
		file2_sym->twin = file1_sym;

		sym1 = file1_sym;

		for_each_sym_continue(e->orig, sym1) {
			if (is_file_symbol(sym1) || !is_local_symbol(sym1))
				break;

			if (dont_correlate(sym1))
				continue;

			sym2 = file2_sym;
			for_each_sym_continue(e->patched, sym2) {
				if (is_file_symbol(sym2) || !is_local_symbol(sym2))
					break;

				if (sym2->twin || dont_correlate(sym2))
					continue;

				if (strcmp(sym1->demangled_name, sym2->demangled_name))
					continue;

				sym1->twin = sym2;
				sym2->twin = sym1;
				break;
			}
		}
	}

	/* Correlate globals */
	for_each_sym(e->orig, sym1) {
		if (sym1->bind == STB_LOCAL)
			continue;

		sym2 = find_global_symbol_by_name(e->patched, sym1->name);

		if (sym2 && !sym2->twin && !strcmp(sym1->name, sym2->name)) {
			sym1->twin = sym2;
			sym2->twin = sym1;
		}
	}

	for_each_sym(e->orig, sym1) {
		if (sym1->twin || dont_correlate(sym1))
			continue;
		WARN("no correlation: %s", sym1->name);
	}
}

/* "sympos" is used by livepatch to disambiguate duplicate symbol names */
static unsigned long find_sympos(struct elf *elf, struct symbol *sym)
{
	unsigned long sympos = 0, nr_matches = 0;
	bool has_dup = false;
	struct symbol *s;

	if (sym->bind != STB_LOCAL)
		return 0;

	for_each_sym(elf, s) {
		if (!strcmp(s->name, sym->name)) {
			nr_matches++;
			if (s == sym)
				sympos = nr_matches;
			else
				has_dup = true;
		}
	}

	if (!sympos)
		ERROR("can't find sympos for %s", sym->name);

	return has_dup ? sympos : 0;
}

static void clone_sym_relocs(struct elfs *e, struct symbol *sym_patched);

static struct symbol *__clone_symbol(struct elf *elf, struct symbol *sym_patched,
				     bool data_too)
{
	struct section *sec = NULL;
	unsigned long offset = 0;
	struct symbol *sym;

	if (data_too && sym_has_section(sym_patched)) {
		struct section *sec_patched = sym_patched->sec;

		sec = find_section_by_name(elf, sec_patched->name);
		if (!sec)
			sec = elf_create_section(elf, sec_patched->name, 0,
						 sec_patched->sh.sh_entsize,
						 sec_patched->sh.sh_type,
						 sec_patched->sh.sh_addralign,
						 sec_patched->sh.sh_flags);

		if (is_string_section(sym_patched->sec)) {
			sym = elf_create_section_symbol(elf, sec);
			goto sym_created;
		}

		if (!is_section_symbol(sym_patched))
			offset = sec_size(sec);

		if (sym_patched->len || is_section_symbol(sym_patched)) {
			void *data = NULL;
			size_t size;

			// bss doesn't have data
			if (sym_patched->sec->data->d_buf)
				data = sym_patched->sec->data->d_buf + sym_patched->offset;

			if (is_section_symbol(sym_patched))
				size = sec_size(sym_patched->sec);
			else
				size = sym_patched->len;

			elf_add_data(elf, sec, data, size);
		}
	}

	sym = elf_create_symbol(elf, sym_patched->name, sec, sym_patched->bind,
				sym_patched->type, offset, sym_patched->len);

sym_created:
	sym_patched->clone = sym;
	sym->clone = sym_patched;

	return sym;
}

/*
 * Copy a symbol to the output object, optionally including its data and
 * relocations.
 */
static struct symbol *clone_symbol(struct elfs *e, struct symbol *sym_patched,
				   bool data_too)
{
	if (sym_patched->clone)
		return sym_patched->clone;

	/* Clone prefix symbol */
	if (data_too && is_function_symbol(sym_patched) && sym_patched->offset) {
		struct symbol *pfx_patched;

		pfx_patched = sec_prev_sym(sym_patched->sec, sym_patched);

		if (pfx_patched && is_prefix_symbol(pfx_patched))
			__clone_symbol(e->out, pfx_patched, true);
	}

	__clone_symbol(e->out, sym_patched, data_too);

	if (data_too)
		clone_sym_relocs(e, sym_patched);

	return sym_patched->clone;
}

/*
 * Copy all changed functions (and their dependencies) from the patched object
 * to the output object.
 */
static int mark_changed_functions(struct elfs *e)
{
	struct symbol *sym_orig, *sym_patched;
	bool changed = false;

	/* Find changed functions */
	for_each_sym(e->orig, sym_orig) {
		if (!is_function_symbol(sym_orig) || is_prefix_symbol(sym_orig))
			continue;

		if (!sym_orig->twin)
			continue;

		if (sym_orig->checksum != sym_orig->twin->checksum) {
			printf("%s: changed: %s\n", Objname, sym_orig->name);
			sym_orig->twin->changed = 1;
			changed = true;
		}
	}

	/* Find added functions */
	for_each_sym(e->patched, sym_patched) {
		if (!is_function_symbol(sym_patched) || is_prefix_symbol(sym_patched))
			continue;

		if (!sym_patched->twin) {
			printf("%s: added: %s\n", Objname, sym_patched->name);
			sym_patched->added = 1;
			changed = true;
		}
	}

	return !changed ? -1 : 0;
}

static void clone_changed_functions(struct elfs *e)
{
	struct symbol *sym_patched;

	/* Clone changed and added functions */
	for_each_sym(e->patched, sym_patched) {
		if (sym_patched->changed || sym_patched->added)
			clone_symbol(e, sym_patched, true);
	}
}

/*
 * Determine whether a relocation should reference the section rather than the
 * underlying symbol.
 */
static bool section_reference_needed(struct section *sec)
{
	/*
	 * String symbols are zero-length and uncorrelated.  It's easier to
	 * deal with them as section symbols.
	 */
	if (is_string_section(sec))
		return true;

	/*
	 * .rodata has mostly anonymous data so there's no way to determine the
	 * length of a needed reference.  just copy the whole section.
	 */
	if (!strcmp(sec->name, ".rodata"))
		return true;

	/* UBSAN anonymous data */
	if (strstarts(sec->name, ".data..Lubsan"))
		return true;

	return false;
}

static bool is_reloc_allowed(struct reloc *reloc)
{
	return section_reference_needed(reloc->sym->sec) ==
	       is_section_symbol(reloc->sym);
}

static struct export *find_export(struct elf *elf, struct symbol *sym)
{
	struct export *export;

	hash_for_each_possible(exports, export, hash, str_hash(sym->name)) {
		if (!strcmp(export->sym, sym->name))
			return export;
	}

	return NULL;
}

static const char *__find_modname(struct elfs *e)
{
	struct section  *sec;
	char *name;

	sec = find_section_by_name(e->orig, ".modinfo");
	if (!sec)
		ERROR("missing .modinfo section");

	name = memmem(sec->data, sec_size(sec), "\0name=", 6);
	if (name)
		return name + 6;

	name = strdup(e->orig->name);
	ERROR_ON(!name, "strdup");

	for (char *c = name; *c; c++) {
		if (*c == '/')
			name = c + 1;
		else if (*c == '-')
			*c = '_';
		else if (*c == '.') {
			*c = '\0';
			break;
		}
	}

	return name;
}

/* Get the object's module name as defined by the kernel (and klp_object) */
static const char *find_modname(struct elfs *e)
{
	static const char *modname;

	if (modname)
		return modname;

	modname = __find_modname(e);
	return modname;
}

static bool klp_reloc_needed(struct elf *elf_patched, struct reloc *reloc_patched)
{
	struct symbol *sym_patched = reloc_patched->sym;
	struct export *export;

	/* no external symbol to reference */
	if (dont_correlate(sym_patched))
		return false;

	/* For cloned functions, a regular reloc will do. */
	if (sym_patched->changed || sym_patched->added)
		return false;

	/*
	 * If exported by a module, it has to be a klp reloc.  Thanks to the
	 * clusterfoot that is late module patching, the patch module is
	 * allowed to be loaded before any modules it depends on.
	 *
	 * If exported by vmlinux, a normal reloc will work.
	 */
	export = find_export(elf_patched, sym_patched);
	if (export)
		return strcmp(export->mod, "vmlinux");

	if (!sym_patched->twin) {
		/*
		 * Presumably the symbol and its reference were added by the
		 * patch.  The symbol could be defined in this .o or in another
		 * .o in the patch module.
		 *
		 * This should be checked *after* the exports, for the case
		 * where the patch adds a reference to an exported symbol.
		 */
		return false;
	}

	/* Unexported symbol which lives in the original vmlinux or module. */
	return true;
}

static int convert_reloc_sym_to_secsym(struct elf *elf, struct reloc *reloc)
{
	struct symbol *sym = reloc->sym;
	struct section *sec = sym->sec;

	if (!sec->sym)
		elf_create_section_symbol(elf, sec);

	reloc->sym = sec->sym;
	set_reloc_sym(elf, reloc, sym->idx);
	set_reloc_addend(elf, reloc, sym->offset + reloc_addend(reloc));
	return 0;
}

static int convert_reloc_secsym_to_sym(struct elf *elf, struct reloc *reloc)
{
	struct symbol *sym = reloc->sym;
	struct section *sec = sym->sec;

	/* If the symbol has a dedicated section, it's easy to find */
	sym = find_symbol_by_offset(sec, 0);
	if (sym && sym->len == sec_size(sec))
		goto found_sym;

	/* No dedicated section; find the symbol manually */
	sym = find_symbol_containing(sec, arch_adjusted_addend(reloc));
	if (!sym) {
		/*
		 * This can happen for special section references to weak code
		 * whose symbol has been stripped by the linker.
		 */
		return -1;
	}

found_sym:
	reloc->sym = sym;
	set_reloc_sym(elf, reloc, sym->idx);
	set_reloc_addend(elf, reloc, reloc_addend(reloc) - sym->offset);
	return 0;
}

/*
 * Convert a relocation symbol reference to the needed format: either a section
 * symbol or the underlying symbol itself.
 */
static int convert_reloc_sym(struct elf *elf, struct reloc *reloc)
{
	if (is_reloc_allowed(reloc))
		return 0;

	if (section_reference_needed(reloc->sym->sec))
		return convert_reloc_sym_to_secsym(elf, reloc);
	else
		return convert_reloc_secsym_to_sym(elf, reloc);
}

/*
 * Convert a regular relocation to a klp relocation (sort of).
 */
static void clone_reloc_klp(struct elfs *e, struct reloc *reloc_patched,
			    struct section *sec, unsigned long offset,
			    struct export *export)
{
	struct symbol *sym_patched = reloc_patched->sym;
	s64 addend = reloc_addend(reloc_patched);
	const char *sym_modname, *sym_orig_name;
	static struct section *klp_relocs;
	struct symbol *sym, *klp_sym;
	unsigned long klp_reloc_off;
	char sym_name[SYM_NAME_LEN];
	struct klp_reloc klp_reloc;
	unsigned long sympos;

	if (!sym_patched->twin)
		ERROR("unexpected klp reloc for new symbol %s", sym_patched->name);

	/*
	 * First, copy the original reloc and symbol as-is so objtool will be
	 * able to process the code correctly during module link time.  This
	 * relocation will be disabled later by cmd_klp_link().
	 */

	sym = sym_patched->clone;
	if (!sym) {
		sym = elf_create_klp_symbol(e->out, sym_patched->name,
					    sym_patched->bind,
					    sym_patched->type);
		sym_patched->clone = sym;
		sym->clone = sym_patched;
	}

	elf_create_reloc(e->out, sec, offset, sym, addend, reloc_type(reloc_patched));

	/*
	 * Second, create the klp symbol.
	 */

	if (export) {
		sym_modname = export->mod;
		sym_orig_name = export->sym;
		sympos = 0;
	} else {
		sym_modname = find_modname(e);
		sym_orig_name = sym_patched->twin->name;
		sympos = find_sympos(e->orig, sym_patched->twin);
	}

	/* symbol format: .klp.sym.modname.sym_name,sympos */
	snprintf(sym_name, SYM_NAME_LEN, KLP_SYM_PREFIX "%s.%s,%ld",
		 sym_modname, sym_orig_name, sympos);

	klp_sym = find_symbol_by_name(e->out, sym_name);
	if (!klp_sym)
		klp_sym = elf_create_klp_symbol(e->out, sym_name,
						sym_patched->bind,
						sym_patched->type);

	/*
	 * Third, create the .klp_relocs entry, which will be converted to an
	 * actual klp rela by cmd_klp_link().
	 *
	 * This intermediate step is necessary to prevent corruption by the
	 * linker, which doesn't know how to properly handle two rela sections
	 * applying to the same base section.
	 */

	if (!klp_relocs)
		klp_relocs = elf_create_section(e->out, KLP_RELOCS_SEC, 0,
						0, SHT_PROGBITS, 8, SHF_ALLOC);

	klp_reloc_off = sec_size(klp_relocs);
	memset(&klp_reloc, 0, sizeof(klp_reloc));

	klp_reloc.type = reloc_type(reloc_patched);
	elf_add_data(e->out, klp_relocs, &klp_reloc, sizeof(klp_reloc));

	/* klp_reloc.offset */
	if (!sec->sym)
		elf_create_section_symbol(e->out, sec);
	elf_create_reloc(e->out, klp_relocs,
			 klp_reloc_off + offsetof(struct klp_reloc, offset),
			 sec->sym, offset, R_ABS64);

	/* klp_reloc.sym */
	elf_create_reloc(e->out, klp_relocs,
			 klp_reloc_off + offsetof(struct klp_reloc, sym),
			 klp_sym, addend, R_ABS64);

}

/* Copy a reloc and its symbol to the output object */
static void clone_reloc(struct elfs *e, struct reloc *reloc_patched,
			struct section *sec, unsigned long offset)
{
	struct symbol *sym_patched = reloc_patched->sym;
	struct export *export = find_export(e->out, sym_patched);
	s64 addend = reloc_addend(reloc_patched);
	struct symbol *sym;

	if (!is_reloc_allowed(reloc_patched))
		ERROR_FUNC(reloc_patched->sec->base, reloc_offset(reloc_patched),
			   "missing symbol for reference to %s+0x%lx",
			   sym_patched->name, addend);

	if (klp_reloc_needed(e->patched, reloc_patched)) {
		clone_reloc_klp(e, reloc_patched, sec, offset, export);
		return;
	}

	sym = clone_symbol(e, sym_patched, !export);

	if (is_string_section(sym_patched->sec))
		addend = elf_add_string(e->out, sym->sec,
					reloc_patched->sym->sec->data->d_buf + addend);

	elf_create_reloc(e->out, sec, offset, sym, addend, reloc_type(reloc_patched));
}

/* Copy all relocs needed for a symbol's contents */
static void clone_sym_relocs(struct elfs *e, struct symbol *sym_patched)
{
	struct section *rsec_patched = sym_patched->sec->rsec;
	struct reloc *reloc_patched;
	unsigned long start, end;
	struct symbol *sym;

	sym = sym_patched->clone;
	if (!sym)
		ERROR("no clone for %s", sym_patched->name);

	if (!rsec_patched)
		return;

	if (!is_section_symbol(sym_patched) && !sym_patched->len)
		return;

	if (is_string_section(sym_patched->sec))
		return;

	if (is_section_symbol(sym_patched)) {
		start = 0;
		end = sec_size(sym_patched->sec);
	} else {
		start = sym_patched->offset;
		end = start + sym_patched->len;
	}

	for_each_reloc(rsec_patched, reloc_patched) {
		unsigned long offset;

		if (reloc_offset(reloc_patched) < start ||
		    reloc_offset(reloc_patched) >= end)
			continue;

		convert_reloc_sym(e->patched, reloc_patched);

		offset = sym->offset + (reloc_offset(reloc_patched) - sym_patched->offset);

		clone_reloc(e, reloc_patched, sym->sec, offset);
	}
}

/* Keep a special section entry if it references an included function */
static bool should_keep_special_sym(struct elf *elf, struct symbol *sym)
{
	struct reloc *reloc;

	if (is_section_symbol(sym))
		return false;

	for_each_reloc(sym->sec->rsec, reloc) {
		unsigned long reloc_off = reloc_offset(reloc);

		if (convert_reloc_sym(elf, reloc))
			continue;

		if (reloc_off >= sym->offset && reloc_off < sym->offset + sym->len &&
		    is_function_symbol(reloc->sym) &&
		    (reloc->sym->changed || reloc->sym->added))
			return true;
	}

	return false;
}

static unsigned int reloc_size(struct reloc *reloc)
{
	switch (reloc_type(reloc)) {

	case R_X86_64_PC32:
	case R_X86_64_32:
		return 4;

	case R_X86_64_64:
	case R_X86_64_PC64:
		return 8;

	default:
		ERROR("unknown reloc type");
	}
}

static void clone_special_section(struct elfs *e, struct section *sec_patched)
{
	unsigned long off_patched, off_out;
	struct reloc *reloc_patched;
	struct symbol *sym_patched;
	bool has_syms = false;
	struct section *sec;

	/*
	 * Some special sections are composed of an array of structs, where
	 * each array entry has its own fake symbol denoting its location and
	 * size.  Copy all entries (both data and relocs) referencing an
	 * included function.
	 */
	off_patched = 0;
	sec_for_each_sym(sec_patched, sym_patched) {
		if (!is_object_symbol(sym_patched))
			continue;
		has_syms = true;

		if (off_patched != sym_patched->offset)
			ERROR("%s+0x%lx: fake symbol gap", sec_patched->name, off_patched);

		off_patched = sym_patched->offset + sym_patched->len;

		if (!should_keep_special_sym(e->patched, sym_patched))
			continue;

		clone_symbol(e, sym_patched, true);
	}

	if (has_syms)
		return;

	/*
	 * Some special sections are just a simple array of pointers.  Copy all
	 * relocs referencing included functions.
	 */
	off_patched = 0;
	off_out = 0;
	sec = NULL;
	for_each_reloc(sec_patched->rsec, reloc_patched) {
		unsigned int rel_size = reloc_size(reloc_patched);

		if (off_patched != reloc_offset(reloc_patched))
			ERROR("%s+0x%lx: reloc gap - does it need fake symbols?",
			      sec_patched->name, off_patched);

		off_patched += rel_size;

		if (convert_reloc_sym(e->patched, reloc_patched))
			continue;

		if (!reloc_patched->sym->changed && !reloc_patched->sym->added)
			continue;

		if (!sec) {
			sec = find_section_by_name(e->out, sec_patched->name);
			if (sec)
				ERROR("why does %s already exist?", sec_patched->name);

			sec = elf_create_section(e->out, sec_patched->name, 0,
						 sec_patched->sh.sh_entsize,
						 sec_patched->sh.sh_type,
						 sec_patched->sh.sh_addralign,
						 sec_patched->sh.sh_flags);
		}

		elf_add_data(e->out, sec, NULL, rel_size);
		clone_reloc(e, reloc_patched, sec, off_out);
		off_out += rel_size;
	}
}

/* Extract only the needed bits from special sections */
static void clone_special_sections(struct elfs *e)
{
	struct section *sec_patched;

	for_each_sec(e->patched, sec_patched) {
		if (is_special_section(sec_patched))
			clone_special_section(e, sec_patched);
	}
}

/*
 * Create __klp_objects and __klp_funcs sections which are intermediate
 * sections provided as input to the patch module's init code (module.c) for
 * building the 'struct klp_patch' needed for the livepatch API.
 */
static void create_klp_sections(struct elfs *e)
{
	size_t obj_size  = sizeof(struct klp_object_ext);
	size_t func_size = sizeof(struct klp_func_ext);
	struct section *obj_sec, *funcs_sec, *str_sec;
	struct symbol *funcs_sym, *str_sym, *sym;
	const char *modname = find_modname(e);
	char sym_name[SYM_NAME_LEN];
	unsigned int nr_funcs = 0;
	void *obj_data;
	s64 addend;

	obj_sec  = elf_create_section_pair(e->out, KLP_OBJECTS_SEC, obj_size, 0, 0);

	funcs_sec = elf_create_section_pair(e->out, KLP_FUNCS_SEC, func_size, 0, 0);
	funcs_sym = elf_create_section_symbol(e->out, funcs_sec);

	str_sec = elf_create_section(e->out, KLP_STRINGS_SEC, 0, 0,
				     SHT_PROGBITS, 1,
				     SHF_ALLOC | SHF_STRINGS | SHF_MERGE);
	elf_add_string(e->out, str_sec, "");
	str_sym = elf_create_section_symbol(e->out, str_sec);

	/* allocate klp_object_ext */
	obj_data = elf_add_data(e->out, obj_sec, NULL, obj_size);

	/* klp_object_ext.name */
	if (strcmp(modname, "vmlinux")) {
		addend = elf_add_string(e->out, str_sec, modname);
		elf_create_reloc(e->out, obj_sec,
				 offsetof(struct klp_object_ext, name),
				 str_sym, addend, R_ABS64);
	}

	/* klp_object_ext.funcs */
	elf_create_reloc(e->out, obj_sec, offsetof(struct klp_object_ext, funcs),
			 funcs_sym, 0, R_ABS64);

	for_each_sym(e->out, sym) {
		unsigned long offset = nr_funcs * func_size;
		unsigned long sympos;
		void *func_data;

		if (!sym->clone || !sym->clone->changed || !is_function_symbol(sym))
			continue;

		/* allocate klp_func_ext */
		func_data = elf_add_data(e->out, funcs_sec, NULL, func_size);

		/* klp_func_ext.old_name */
		addend = elf_add_string(e->out, str_sec, sym->clone->twin->name);
		elf_create_reloc(e->out, funcs_sec,
				 offset + offsetof(struct klp_func_ext, old_name),
				 str_sym, addend, R_ABS64);

		/* klp_func_ext.new_func */
		elf_create_reloc(e->out, funcs_sec,
				 offset + offsetof(struct klp_func_ext, new_func),
				 sym, 0, R_ABS64);

		/* klp_func_ext.sympos */
		BUILD_BUG_ON(sizeof(sympos) != sizeof_field(struct klp_func_ext, sympos));
		sympos = find_sympos(e->orig, sym->clone->twin);
		memcpy(func_data + offsetof(struct klp_func_ext, sympos), &sympos,
		       sizeof_field(struct klp_func_ext, sympos));

		nr_funcs++;
	}

	/* klp_object_ext.nr_funcs */
	BUILD_BUG_ON(sizeof(nr_funcs) != sizeof_field(struct klp_object_ext, nr_funcs));
	memcpy(obj_data + offsetof(struct klp_object_ext, nr_funcs), &nr_funcs,
	       sizeof_field(struct klp_object_ext, nr_funcs));

	/*
	 * Find callback pointers created by KLP_PRE_PATCH_CALLBACK() and
	 * friends, and add them to the klp object.
	 */

	snprintf(sym_name, SYM_NAME_LEN, KLP_PRE_PATCH_PREFIX "%s", modname);
	sym = find_symbol_by_name(e->out, sym_name);
	if (sym) {
		struct reloc *reloc;

		reloc = find_reloc_by_dest(e->out, sym->sec, sym->offset);

		elf_create_reloc(e->out, obj_sec,
				 offsetof(struct klp_object_ext, callbacks) +
				 offsetof(struct klp_callbacks, pre_patch),
				 reloc->sym, reloc_addend(reloc), R_ABS64);
	}

	snprintf(sym_name, SYM_NAME_LEN, KLP_POST_PATCH_PREFIX "%s", modname);
	sym = find_symbol_by_name(e->out, sym_name);
	if (sym) {
		struct reloc *reloc;

		reloc = find_reloc_by_dest(e->out, sym->sec, sym->offset);

		elf_create_reloc(e->out, obj_sec,
				 offsetof(struct klp_object_ext, callbacks) +
				 offsetof(struct klp_callbacks, post_patch),
				 reloc->sym, reloc_addend(reloc), R_ABS64);
	}

	snprintf(sym_name, SYM_NAME_LEN, KLP_PRE_UNPATCH_PREFIX "%s", modname);
	sym = find_symbol_by_name(e->out, sym_name);
	if (sym) {
		struct reloc *reloc;

		reloc = find_reloc_by_dest(e->out, sym->sec, sym->offset);

		elf_create_reloc(e->out, obj_sec,
				 offsetof(struct klp_object_ext, callbacks) +
				 offsetof(struct klp_callbacks, pre_unpatch),
				 reloc->sym, reloc_addend(reloc), R_ABS64);
	}

	snprintf(sym_name, SYM_NAME_LEN, KLP_POST_UNPATCH_PREFIX "%s", modname);
	sym = find_symbol_by_name(e->out, sym_name);
	if (sym) {
		struct reloc *reloc;

		reloc = find_reloc_by_dest(e->out, sym->sec, sym->offset);

		elf_create_reloc(e->out, obj_sec,
				 offsetof(struct klp_object_ext, callbacks) +
				 offsetof(struct klp_callbacks, post_unpatch),
				 reloc->sym, reloc_addend(reloc), R_ABS64);
	}
}

int cmd_klp_diff(int argc, const char **argv)
{
	struct elfs e;

	argc--;
	argv++;

	if (argc != 3) {
		fprintf(stderr, "usage: objtool diff <in1.o> <in2.o> <out.o>\n");
		return -1;
	}

	e.orig		= elf_open_read(argv[0], O_RDONLY);
	e.patched	= elf_open_read(argv[1], O_RDONLY);
	e.out		= NULL;

	Objname = basename(Objname);

	read_exports();

	read_sym_checksums(e.orig);
	read_sym_checksums(e.patched);

	correlate_symbols(&e);

	if (mark_changed_functions(&e))
		return 0;

	e.out = elf_create_file(&e.orig->ehdr, argv[2]);

	clone_changed_functions(&e);

	clone_special_sections(&e);

	create_klp_sections(&e);

	elf_write(e.out);

	return 0;
}

